carts/urls.py
from django.urls import path

from . import views

app_name = 'carts'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('agregar', views.add, name='add'),
    path('eliminar', views.remove, name='remove')
]

exportellus__web/urls.py
from django.contrib import admin

from django.urls import path
from django.urls import include

from django.conf.urls.static import static
from django.conf import settings

from . import views

from products.views import ProductListView

urlpatterns = [
    path('', ProductListView.as_view(), name='index'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('registro', views.register, name='register'),
    path('admin/', admin.site.urls),
    path('productos/', include('products.urls')),
    path('carrito/', include('carts.urls')),
    path('orden/', include('orders.urls')),
    path('direcciones/', include('shipping_addresses.urls')),
    path('codigos/', include('promo_codes.urls')),
    path('pagos/', include('billing_profiles.urls')),
    #path('profile/', views.update_profile, name='update_profile'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.order, name='order'),
    path('direccion', views.address, name='address'),
    path('seleccionar/direccion', views.select_address, name='select_address'),
    path('establecer/direccion/<int:pk>', views.check_address, name='check_address'),
    path('confirmacion', views.confirm, name='confirm'),
    path('cancelar', views.cancel, name='cancel'),
    path('completar', views.complete, name='complete'),
    path('pago', views.payment, name='payment'),
    path('completados', views.OrderListView.as_view(), name='completeds')
]

products/urls.py
from django.urls import path

from . import views

app_name = 'products'

urlpatterns = [
    path('search', views.ProductSearchListView.as_view(), name='search'),
    path('<slug:slug>', views.ProductDetailView.as_view(), name='product'), #id -> llave primaria
]

carts/models.py
import uuid
import decimal

from django.db import models

from users.models import User
from products.models import Product

from orders.common import OrderStatus

from django.db.models.signals import pre_save
from django.db.models.signals import post_save
from django.db.models.signals import m2m_changed

class Cart(models.Model):
    cart_id = models.CharField(max_length=100, null=False, blank=False, unique=True)
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product, through='CartProducts')
    subtotal = models.DecimalField(default=0.0, max_digits=8, decimal_places=2)
    total = models.DecimalField(default=0.0, max_digits=8, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)

    FEE = 0.05 # 0.5%

    def __str__(self):
        return self.cart_id

    def update_totals(self):
        self.update_subtotal()
        self.update_total()

        if self.order:
            self.order.update_total()

    def update_subtotal(self):
        self.subtotal = sum([
            cp.quantity * cp.product.price for cp in self.products_related()
         ])
        self.save()

    def update_total(self):
        self.total = self.subtotal + (self.subtotal * decimal.Decimal(Cart.FEE) )
        self.save()

    def products_related(self):
        return self.cartproducts_set.select_related('product')

    def has_products(self):
        return self.products.exists()

    @property
    def order(self):
        return self.order_set.filter(status=OrderStatus.CREATED).first()

class CartProductsManager(models.Manager):

    def create_or_update_quantity(self, cart, product, quantity=1):
        object, created = self.get_or_create(cart=cart, product=product)

        if not created:
            quantity = object.quantity + quantity

        object.update_quantity(quantity)
        return object

class CartProducts(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True)

    objects = CartProductsManager()

    def update_quantity(self, quantity=1):
        self.quantity = quantity
        self.save()

def set_cart_id(sender, instance, *args, **kwargs):
    if not instance.cart_id:
        instance.cart_id = str(uuid.uuid4())

def update_totals(sender, instance, action, *args, **kwargs):
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
        instance.update_totals()

def post_save_update_totals(sender, instance, *args, **kwargs):
    instance.cart.update_totals()

pre_save.connect(set_cart_id, sender=Cart)
post_save.connect(post_save_update_totals, sender=CartProducts)
m2m_changed.connect(update_totals, sender=Cart.products.through)

carts/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404

from .models import CartProducts
from products.models import Product
from .utils import get_or_create_cart

def cart(request):
    cart = get_or_create_cart(request)

    return render(request, 'carts/cart.html', {
        'cart': cart
    })

def add(request):
    cart = get_or_create_cart(request)
    product = get_object_or_404(Product, pk=request.POST.get('product_id'))
    quantity = int(request.POST.get('quantity', 1))

    # cart.products.add(product, through_defaults={
    #     'quantity': quantity
    # })
    cart_product = CartProducts.objects.create_or_update_quantity(cart=cart,
                                                                    product=product,
                                                                    quantity=quantity)

    return render(request, 'carts/add.html', {
        'quantity': quantity,
        'cart_product': cart_product,
        'product': product
    })

def remove(request):
    cart = get_or_create_cart(request)
    product = get_object_or_404(Product, pk=request.POST.get('product_id'))

    cart.products.remove(product)

    return redirect('carts:cart')

carts/templates/carts/add.html
{% extends 'base.html' %}
{% load static %}
{% load cart_extras %}



{% block content %}

    <!--breadcrumbs area start-->
    <div class="breadcrumbs_area">
      <div class="container">   
          <div class="row">
              <div class="col-12">
                  <div class="breadcrumb_content">
                     <h3 style="font-size: 25px;">EL PRODUCTO HA SIDO AGREGADO CON EXITO</h3>
                  </div>
              </div>
          </div>
      </div>         
  </div>
  <!--breadcrumbs area end-->
  
   <!--shopping cart area start -->
  <div class="shopping_cart_area">
      <div class="container">  
          <form action="#"> 
              <div class="row">
                  <div class="col-12">
                      <div class="table_desc">
                          <div class="cart_page table-responsive">
                              <table>
                                  <thead>
                                      <tr>
                                          <th class="product_thumb">Imagen</th>
                                          <th class="product_name">Producto</th>
                                          <th class="product-price">Precio</th>
                                          <th class="product_quantity">Cantidad</th>
                                      </tr>
                                  </thead>
                                  <tbody>
                                      <tr>
                                          <td class="product_thumb">
                                            {% if product.image %}
                                                <a href=""><img src="{{ product.image.url }}" alt="Imagen del producto"></a>
                                            {% endif %}
                                            </td>
                                          <td class="product_name"><a href="{% url 'products:product' product.slug %}">{{ product.title }}</a></td>
                                          <td class="product-price">${{ product.price }}</td>
                                          <td class="product_quantity">{{ quantity | quantity_add_format }}</td> 
                                      </tr>
                                  </tbody>
                              </table>   
                          </div>      
                      </div>
                      <div class="boton-add">
                          <a href="{% url 'carts:cart' %}">Ver carrito</a>
                          <a href="{% url 'index' %}">Seguir comprando</a>
                      </div>
                   </div>
               </div>
          </form> 
      </div>     
  </div>
   <!--shopping cart area end -->

{% endblock %}

carts/templates/carts/cart.html
{% extends 'base.html' %}
{% load product_extras %}



{% block content %}
    <!--breadcrumbs area start-->
    <div class="breadcrumbs_area">
        <div class="container">   
            <div class="row">
                <div class="col-12">
                    <div class="breadcrumb_content">
                       <h3>CARRITO</h3>
                    </div>
                </div>
            </div>
        </div>         
    </div>
    <!--breadcrumbs area end-->
    {% if cart.products.exists %} 
        <!--shopping cart area start -->
        <div class="shopping_cart_area">
            <div class="container">  
                <div> 
                    <div class="row">
                        <div class="col-12">
                            <div class="table_desc">
                                <div class="cart_page table-responsive">
                                    <table>
                                        <thead>
                                            <tr>
                                                <th class="product_number">#</th>
                                                <th class="product_remove">Eliminar</th>
                                                <th class="product_thumb">Imagen</th>
                                                <th class="product_name">Producto</th>
                                                <th class="product-price">Precio</th>
                                                <th class="product_quantity">Cantidad</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for cp in cart.products_related %}
                                                {% with product=cp.product %}
                                                    <tr>
                                                        <td class="product_number">{{ forloop.counter }}</td>
                                                        <td class="product_remove">{% include 'carts/snippets/remove.html' %}</td>
                                                        <td class="product_thumb">
                                                            <a href="">
                                                                {% if product.image %}
                                                                    <img src="{{ product.image.url }}" alt="Imagen del producto">
                                                                {% endif %}
                                                            </a>
                                                        </td>
                                                        <td class="product_name"><a href="{% url 'products:product' product.slug %}">{{ product.title }}</a></td>
                                                        <td class="product-price">{{ product.price | price_format }}</td>
                                                        <td class="product_quantity">{{ cp.quantity }}</td>
                                                    </tr>
                                                {% endwith %}
                                            {% endfor %}
                                        </tbody>
                                    </table>   
                                </div>        
                            </div>
                        </div>
                    </div>
                    <!--coupon code area start-->
                    <div class="coupon_area">
                        <div class="row">
                            <div class="col-lg-6 col-md-6">
                                <div class="coupon_code right">
                                    <h3>Balance final</h3>
                                    <div class="coupon_inner">
                                    <div class="cart_subtotal">
                                        <p>Subtotal</p>
                                        Subtotal ({{ cart.products.count }}): <p class="cart_amount"> {{ cart.subtotal | price_format }}</p>
                                    </div>
                                    <div class="checkout_btn">
                                            <a href="{% url 'orders:order' %}" class="btn btn-warning">Proceder al pago</a>
                                    </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!--coupon code area end-->
                </div> 
            </div>     
        </div>
        <!--shopping cart area end -->
    {% else %}
        <div class="error_cart">
            <h2>Ups! Tu carrito de compras esta vacio</h2> 
            <a href="{% url 'index' %}">Seguir explorando</a>
        </div>
    {% endif %} 
    
        <!--product area start-->
        <div class="product_area mb-65">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="section_title">
                           <h2>Recomendados para ti</h2>
                        </div>
                    </div>
                </div> 
                 <div class="product_container">  
                   <div class="row">
                       <div class="col-12">
                            {% include 'products/snippets/list-index.html' %} 
                        </div>
                    </div>        
                </div>  
            </div> 
        </div>
    <!--product area end-->
    

{% endblock %}