carts/urls.py
from django.urls import path

from . import views

app_name = 'carts'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('agregar', views.add, name='add'),
    path('eliminar', views.remove, name='remove')
]

exportellus__web/urls.py
from django.contrib import admin

from django.urls import path
from django.urls import include

from django.conf.urls.static import static
from django.conf import settings

from . import views

from products.views import ProductListView

urlpatterns = [
    path('', ProductListView.as_view(), name='index'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('registro', views.register, name='register'),
    path('admin/', admin.site.urls),
    path('productos/', include('products.urls')),
    path('carrito/', include('carts.urls')),
    path('orden/', include('orders.urls')),
    path('direcciones/', include('shipping_addresses.urls')),
    path('codigos/', include('promo_codes.urls')),
    path('pagos/', include('billing_profiles.urls')),
    #path('profile/', views.update_profile, name='update_profile'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path

from . import views

app_name = 'products'

urlpatterns = [
    path('search', views.ProductSearchListView.as_view(), name='search'),
    path('<slug:slug>', views.ProductDetailView.as_view(), name='product'), #id -> llave primaria
]

products/models.py
import uuid

from django.db import models
from django.utils.text import slugify
from django.db.models.signals import pre_save

class Product(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField()
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0.0)
    slug = models.SlugField(null=False, blank=False, unique=True)
    image = models.ImageField(upload_to='products/', null=False, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)

    # def save(self, *args, **kwargs):
    #     self.slug = slugify(self.title)
    #     super(Product, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

def set_slug(sender, instance, *args, **kwargs): #callback
    if instance.title and not instance.slug:
        slug = slugify(instance.title)

        while Product.objects.filter(slug=slug).exists():
            slug = slugify(
                '{}-{}'.format(instance.title, str(uuid.uuid4())[:8] )
            )

        instance.slug = slug

pre_save.connect(set_slug, sender=Product)

products/views.py
from django.shortcuts import render

from django.db.models import Q

from django.views.generic.list import ListView
from django.views.generic.detail import DetailView

from .models import Product

class ProductListView(ListView):
    template_name = 'index.html'
    queryset = Product.objects.all().order_by('-id')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['message'] = 'Listado de productos'

        return context

class ProductDetailView(DetailView): #id -> pk
    model = Product
    template_name = 'products/product.html'

class ProductSearchListView(ListView):
    template_name = 'products/search.html'

    def get_queryset(self):
        filters = Q(title__icontains=self.query()) | Q(category__title__icontains=self.query())
        return Product.objects.filter(filters)

    def query(self):
        return self.request.GET.get('q')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['query'] = self.query()
        context['count'] = context['product_list'].count()

        return context

products/templates/products/snippets/list-index.html
  <div class="product_carousel product_column5 owl-carousel">
    {% for object in product_list %}
        <div class="product_items">
            {% include 'products/snippets/product.html' with product=object %}
            {% include 'products/snippets/product.html' with product=object %}
        </div>
        <div class="product_items">
            {% include 'products/snippets/product.html' with product=object %}
            {% include 'products/snippets/product.html' with product=object %}
        </div>
        <div class="product_items">
            {% include 'products/snippets/product.html' with product=object %}
            {% include 'products/snippets/product.html' with product=object %}
        </div>
        <div class="product_items">
            {% include 'products/snippets/product.html' with product=object %}
            {% include 'products/snippets/product.html' with product=object %}
        </div>
        <div class="product_items">
            {% include 'products/snippets/product.html' with product=object %}
            {% include 'products/snippets/product.html' with product=object %}
        </div>
        <div class="product_items">
            {% include 'products/snippets/product.html' with product=object %}
            {% include 'products/snippets/product.html' with product=object %}
        </div>
        {% endfor %}
  </div>  

products/templates/products/snippets/list.html
    <!--shop  area start-->
    <div class="shop_area shop_reverse mt-70 mb-70">
      <div class="container">
          <div class="row">
              <div class="col-lg-3 col-md-12">
                 <!--sidebar widget start-->
                 <!--sidebar widget start-->
                 <aside class="sidebar_widget">
                  <div class="widget_inner">
                      <div class="widget_list widget_filter">
                          <h3>Filter by price</h3>
                          <form action="#"> 
                              <div id="slider-range"></div>   
                              <button type="submit">Filter</button>
                              <input type="text" name="text" id="amount" />   

                          </form> 
                      </div>
                      <div class="widget_list widget_color">
                          <h3>Ubicacion</h3>
                          <ul>
                              <li>
                                  <a href="#">Ecuador  <span>(6)</span></a> 
                              </li>
                              <li>
                                  <a href="#"> Argentina <span>(8)</span></a> 
                              </li>
                              <li>
                                  <a href="#">Peru <span>(10)</span></a> 
                              </li>
                              <li>
                                  <a href="#"> Bollivia <span>(6)</span></a> 
                              </li>
                              <li>
                                  <a href="#">Chile <span>(4)</span></a> 
                              </li>
                            
                          </ul>
                      </div>
                    </div>
              </aside>
                  <!--sidebar widget end-->
              </div>
              <div class="col-lg-9 col-md-12">
                  <!--shop wrapper start-->
                  <!--shop toolbar start-->
                  <div class="shop_toolbar_wrapper">
                      <div class="shop_toolbar_btn">

                          <button data-role="grid_3" type="button" class=" btn-grid-3" data-toggle="tooltip" title="3"></button>

                          <button data-role="grid_4" type="button"  class=" btn-grid-4" data-toggle="tooltip" title="4"></button>

                          <button data-role="grid_list" type="button"  class="active btn-list" data-toggle="tooltip" title="List"></button>
                      </div>
                      <div class=" niceselect_option">
                          <form class="select_option" action="#">
                              <select name="orderby" id="short">

                                  <option selected value="1">Sort by average rating</option>
                                  <option  value="2">Sort by popularity</option>
                                  <option value="3">Sort by newness</option>
                                  <option value="4">Sort by price: low to high</option>
                                  <option value="5">Sort by price: high to low</option>
                                  <option value="6">Product Name: Z</option>
                              </select>
                          </form>
                      </div>
                      <div class="page_amount">
                          <p>Showing 1–9 of 21 results</p>
                      </div>
                  </div>
                   <!--shop toolbar end-->
                   <div class="row shop_wrapper grid_list">
                    {% for object in product_list %}
                    {% include 'products/snippets/productsearch.html' with product=object %}
                    {% endfor %}
                    </div>

                  <div class="shop_toolbar t_bottom">
                      <div class="pagination">
                          <ul>
                              <li class="current">1</li>
                              <li><a href="#">2</a></li>
                              <li><a href="#">3</a></li>
                              <li class="next"><a href="#">next</a></li>
                              <li><a href="#">>></a></li>
                          </ul>
                      </div>
                  </div>
                  <!--shop toolbar end-->
                  <!--shop wrapper end-->
              </div>
          </div>
      </div>
  </div>
  <!--shop  area end-->

  {% include 'products/snippets/pop-up.html' %}

products/templates/products/snippets/list1.html
    <!--shop  area start-->
    <div class="shop_area shop_reverse mt-70 mb-70">
      <div class="container">
          <div class="row">
              <div class="col-lg-3 col-md-12">
                 <!--sidebar widget start-->
                 <!--sidebar widget start-->
                 <aside class="sidebar_widget">
                  <div class="widget_inner">
                      <div class="widget_list widget_filter">
                          <h3>Filter by price</h3>
                          <form action="#"> 
                              <div id="slider-range"></div>   
                              <button type="submit">Filter</button>
                              <input type="text" name="text" id="amount" />   

                          </form> 
                      </div>
                      <div class="widget_list widget_color">
                          <h3>Ubicacion</h3>
                          <ul>
                              <li>
                                  <a href="#">Ecuador  <span>(6)</span></a> 
                              </li>
                              <li>
                                  <a href="#"> Argentina <span>(8)</span></a> 
                              </li>
                              <li>
                                  <a href="#">Peru <span>(10)</span></a> 
                              </li>
                              <li>
                                  <a href="#"> Bollivia <span>(6)</span></a> 
                              </li>
                              <li>
                                  <a href="#">Chile <span>(4)</span></a> 
                              </li>
                            
                          </ul>
                      </div>
                    </div>
              </aside>
                  <!--sidebar widget end-->
              </div>
              <div class="col-lg-9 col-md-12">
                  <!--shop wrapper start-->
                  <!--shop toolbar start-->
                  <div class="shop_toolbar_wrapper">
                      <div class="shop_toolbar_btn">

                          <button data-role="grid_3" type="button" class=" btn-grid-3" data-toggle="tooltip" title="3"></button>

                          <button data-role="grid_4" type="button"  class=" btn-grid-4" data-toggle="tooltip" title="4"></button>

                          <button data-role="grid_list" type="button"  class="active btn-list" data-toggle="tooltip" title="List"></button>
                      </div>
                      <div class=" niceselect_option">
                          <form class="select_option" action="#">
                              <select name="orderby" id="short">

                                  <option selected value="1">Sort by average rating</option>
                                  <option  value="2">Sort by popularity</option>
                                  <option value="3">Sort by newness</option>
                                  <option value="4">Sort by price: low to high</option>
                                  <option value="5">Sort by price: high to low</option>
                                  <option value="6">Product Name: Z</option>
                              </select>
                          </form>
                      </div>
                      <div class="page_amount">
                          <p>Showing 1–9 of 21 results</p>
                      </div>
                  </div>
                   <!--shop toolbar end-->
                   <div class="row shop_wrapper grid_list">
                    {% for object in product_list %}
                    {% include 'products/snippets/productsearch.html' with product=object %}
                   </div>
                    {% endfor %}

                  <div class="shop_toolbar t_bottom">
                      <div class="pagination">
                          <ul>
                              <li class="current">1</li>
                              <li><a href="#">2</a></li>
                              <li><a href="#">3</a></li>
                              <li class="next"><a href="#">next</a></li>
                              <li><a href="#">>></a></li>
                          </ul>
                      </div>
                  </div>
                  <!--shop toolbar end-->
                  <!--shop wrapper end-->
              </div>
          </div>
      </div>
  </div>
  <!--shop  area end-->

products/templates/products/snippets/pop-up.html
{% load static %}
<!-- modal area start-->
    <div class="modal fade" id="modal_box" tabindex="-1" role="dialog"  aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true"><i class="icon-x"></i></span>
                </button>
                <div class="modal_body">
                    <div class="container">
                        <div class="row">
                            <div class="col-lg-5 col-md-5 col-sm-12">
                                    <div class="modal_tab"> 
                                            <div class="tab-content product-details-large">
                                                <div class="tab-pane fade show active" id="tab1" role="tabpanel" >
                                                    <div class="modal_tab_img">
                                                        {% if product.image %}<a href="#"><img src="{{ product.image.url }}" alt=""></a>{% endif %}      
                                                    </div>
                                                </div>
                                            </div> 
                                    </div>
                            </div> 
                            <div class="col-lg-7 col-md-7 col-sm-12">
                                <div class="modal_right">
                                    <div class="modal_title mb-10">
                                        <h2>{{ product.title }}</h2> 
                                    </div>
                                    <div class="modal_price mb-10">
                                        <span class="new_price">{{ product.price }}</span>     
                                    </div>
                                    <div class="modal_description mb-15">
                                        <p>{{ product.description }}</p>    
                                    </div> 
                                    <div class="action_links">
                                        <ul>
                                            
                                        </ul>
                                    </div> 
                                </div>    
                            </div>    
                        </div>     
                    </div>
                </div>    
            </div>
        </div>
    </div>
    <!-- modal area end-->

products/templates/products/snippets/product.html
{% load static %}
<!-- carta de producto -->
<article class="single_product">
    <figure>
        <div class="product_thumb">
            {% if product.image %}
            <a class="primary_img" href="{% url 'products:product' product.slug %}">
              <img src="{{ product.image.url }}" alt="Imagen del producto" height="212px" width="212px">
            </a>
            {% endif %}
            <div class="action_links">
                <a class="boton-product" data-toggle="modal" data-target="#modal_box"><span class="lnr lnr-magnifier"></span> Vista rápida</a>
            </div>
        </div>
        <figcaption class="product_content">
            <h4 class="product_name">{{ product.title }}</h4>
            <p><a href="#">Categoria</a></p>
            <div class="price_box"> 
                <span class="current_price">{{ product.price }}</span>
            </div>
        </figcaption>
    </figure>
  </article>

products/templates/products/snippets/product222.html
{% load static %}
<!-- carta de producto -->
<article class="single_product">
    <figure>
        <div class="product_thumb">
            {% if product.image %}
            <a class="primary_img" href="{% url 'products:product' product.slug %}">
              <img src="{{ product.image.url }}" alt="Imagen del producto" height="212px">
            </a>
            {% endif %}
            <div class="action_links">
                <a class="boton-product" data-toggle="modal" data-target="#modal_box"><span class="lnr lnr-magnifier"></span> Vista rápida</a>
            </div>
        </div>
        <figcaption class="product_content">
            <p><a href="#">Categoria</a></p>
            <div class="price_box"> 
                <span class="current_price">{{ product.price }}</span>
            </div>
        </figcaption>
    </figure>
  </article>

products/templates/products/snippets/product3.html
<!-- Product -->
<div class="card h-100">

    {% if product.image %}
      <img src="{{ product.image.url }}" alt="Imagen del producto" height="300">
    {% endif %}
  
    <div class="card-body">
      <h5 class="card-title">{{ product.title }}</h5>
      <p class="card-text">{{ product.description | truncatewords:15 }}</p>
      <a href="{% url 'products:product' product.slug %}" class="btn btn-primary">Ver más</a>
    </div>
  
  </div>

products/templates/products/snippets/product456.html
{% load static %}
<!-- carta de producto -->
<article class="single_product">
    <figure>
        <div class="product_thumb">
            {% if product.image %}
            <a class="primary_img" href="{% url 'products:product' product.slug %}">
              <img src="{{ product.image.url }}" alt="Imagen del producto" height="212px">
            </a>
            {% endif %}
            <div class="action_links">
                <ul>
                    <li class="add_to_cart"><a href= "{% url 'carts:add' %}" title="Añadir a carrito"><span class="lnr lnr-cart"></span></a></li>
                    <li class="quick_button"><a href="#" data-toggle="modal" data-target="#modal_box"  title="Vista rápida"> <span class="lnr lnr-magnifier"></span></a></li>
                </ul>
            </div>
        </div>
        <figcaption class="product_content">
            <p><a href="#">Categoria</a></p>
            <div class="price_box"> 
                <span class="current_price">{{ product.price }}</span>
            </div>
        </figcaption>
    </figure>
  </article>

products/templates/products/snippets/productsearch.html
<div class="col-12 ">
    <div class="single_product">
        <div class="product_thumb">
                {% if product.image %}
                <a class="primary_img" href="{% url 'products:product' product.slug %}">
                    <img src="{{ product.image.url }}" height="600px">
                </a>
                {% endif %}
                <div class="action_links">
                    <ul>
                        <li class="quick_button"><a href="#" data-toggle="modal" data-target="#modal_box"><span class="lnr lnr-magnifier"></span> Vista rápida</a></li>
                    </ul>
                </div>
        </div>
        <div class="product_content grid_content">
                <h4 class="product_name"><a href="{% url 'products:product' product.slug %}">{{ product.title }}</a></h4>
                <p><a href="#">Categoria</a></p>
                <div class="price_box"> 
                    <span class="current_price">{{ product.price }}</span>
                </div>
            </div>
        <div class="product_content list_content">
            <a href="{% url 'products:product' product.slug %}"><h4 class="product_name">{{ product.title }}</h4></a>
            <p><a href="#">Categoria</a></p>
            <div class="price_box"> 
                <span class="current_price">{{ product.price }}</span>
            </div>
            <div class="product_desc">
                <p>{{ product.description | truncatewords:15 }}</p>
            </div>
            <div class="action_links list_action_right">
                <a class="boton-product" data-toggle="modal" data-target="#modal_box"><span class="lnr lnr-magnifier"></span> Vista rápida</a>
            </div>
        </div>
    </div>
</div>

products/templates/products/snippets/search.html
<form action="{% url 'products:search' %}">
    <div class="hover_category">
         <select class="select_option" name="select" id="categori2">
             <option selected value="1">Ubicación</option>
             <option value="2">Accessories</option>
             <option value="3">Accessories & More</option>
             <option value="4">Butters & Eggs</option>
             <option value="5">Camera & Video </option>
             <option value="6">Mornitors</option>
             <option value="7">Tablets</option>
             <option value="8">Laptops</option>
             <option value="9">Handbags</option>
             <option value="10">Headphone & Speaker</option>
             <option value="11">Herbs & botanicals</option>
             <option value="12">Vegetables</option>
             <option value="13">Shop</option>
             <option value="14">Laptops & Desktops</option>
             <option value="15">Watchs</option>
             <option value="16">Electronic</option>
         </select>
        </div>
         <div class="search_box">
            <input type="text" name="q" value="{{ query }}" placeholder="Search product...">
            <button type="submit" name="" value="Buscar"><span class="lnr lnr-magnifier"></span></button>
        </div>                        
    
    
    

 </form>