billing_profiles/urls.py
from django.urls import path

from . import views

app_name = 'billing_profiles'

urlpatterns = [
    path('', views.BillingProfileListView.as_view(), name='billing_profiles'),
    path('nuevo', views.create, name='create')
]

carts/urls.py
from django.urls import path

from . import views

app_name = 'carts'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('agregar', views.add, name='add'),
    path('eliminar', views.remove, name='remove')
]

exportellus__web/urls.py
from django.contrib import admin

from django.urls import path
from django.urls import include

from django.conf.urls.static import static
from django.conf import settings

from . import views

from products.views import ProductListView

urlpatterns = [
    path('', ProductListView.as_view(), name='index'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('registro', views.register, name='register'),
    path('admin/', admin.site.urls),
    path('productos/', include('products.urls')),
    path('carrito/', include('carts.urls')),
    path('orden/', include('orders.urls')),
    path('direcciones/', include('shipping_addresses.urls')),
    path('codigos/', include('promo_codes.urls')),
    path('pagos/', include('billing_profiles.urls')),
    #path('profile/', views.update_profile, name='update_profile'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.order, name='order'),
    path('direccion', views.address, name='address'),
    path('seleccionar/direccion', views.select_address, name='select_address'),
    path('establecer/direccion/<int:pk>', views.check_address, name='check_address'),
    path('confirmacion', views.confirm, name='confirm'),
    path('cancelar', views.cancel, name='cancel'),
    path('completar', views.complete, name='complete'),
    path('pago', views.payment, name='payment'),
    path('completados', views.OrderListView.as_view(), name='completeds')
]

products/urls.py
from django.urls import path

from . import views

app_name = 'products'

urlpatterns = [
    path('search', views.ProductSearchListView.as_view(), name='search'),
    path('<slug:slug>', views.ProductDetailView.as_view(), name='product'), #id -> llave primaria
]

shipping_addresses/urls.py
from django.urls import path

from . import views

app_name = 'shipping_addresses'

urlpatterns = [
    path('', views.ShippingAddressListView.as_view(), name='shipping_addresses'),
    path('nuevo', views.create, name='create'),
    path('editar/<int:pk>', views.ShippingAddressUpdateView.as_view(), name='update'),
    path('eliminar/<int:pk>', views.ShippingAddressDeleteView.as_view(), name='delete'),
    path('default/<int:pk>', views.default, name='default')
]

templates/Log_In.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/Estilo_Log_In.css' %}">
    <title>Log In</title>
  </head>
  <body>
    <div id="logreg-forms">
        {% if messages %}
            {% for message in messages %}
        
        
        <div class="alert {% if message.tags == 'succes' %}alert-succes{%else%}alert-danger{%endif%}">
            <button type="button" class="close" data-dismiss="alert">x</button>

            {{ message }}

        </div>
            {% endfor %}
        {% endif %}
        <form class="form-signin" method = "post">
            {% csrf_token %}
            <h1 class="h3 mb-3 font-weight-normal" style="text-align: center">Exportellus</h1>
            <div class="social-login">
                <!-- B O T O N  D E  F A C E B O O K -->           <!-- B O T O N  D E  F A C E B O O K -->         <!-- B O T O N  D E  F A C E B O O K -->
                <button class="btn facebook-btn social-btn" type="button"><span><i class="fab fa-facebook-f"></i> Sign in with Facebook</span> </button>
                
                <!-- B O T O N  D E  G O O G L E -->           <!-- B O T O N  D E  G O O G L E -->         <!-- B O T O N  D E  G O O G L E -->
                <button class="btn google-btn social-btn" type="button"><span><i class="fab fa-google-plus-g"></i> Sign in with Google+</span> </button>
            </div>
            <p style="text-align:center"> OR  </p>

            <!--  CUADRO DE TEXTO CUADRO DE TEXTO E - M A I L -->           <!-- CUADRO DE TEXTO CUADRO DE TEXTO E - M A I L -->         <!-- CUADRO DE TEXTO CUADRO DE TEXTO E - M A I L -->
            <input type="text" name="username" class="form-control" placeholder="Email o Usuario" required="" autofocus="">

            <!-- CUADRO DE TEXTO C O N T R A S E N A -->           <!-- CUADRO DE TEXTO C O N T R A S E N A -->         <!-- CUADRO DE TEXTO C O N T R A S E N A -->
            <input type="password" name="password" class="form-control" placeholder="Password" required="">
            
            <!-- B O T O N  S I G N  IN -->           <!-- B O T O N  S I G N  IN -->         <!-- B O T O N  S I G N  IN -->
            <button class="btn btn-success btn-block" type="submit"><i class="fas fa-sign-in-alt"></i> Sign in</button>

            <!-- BOTON OLVIDASTE LA CONTRASENA? -->           <!-- BOTON OLVIDASTE LA CONTRASENA? -->         <!-- BOTON OLVIDASTE LA CONTRASENA? --> 
            <a href="#" id="forgot_pswd">Forgot password?</a>
            <hr>

            <!-- BOTON SIGN UP NEW ACOUNT  -->          <!-- BOTON SIGN UP NEW ACOUNT  -->        <!-- BOTON SIGN UP NEW ACOUNT  -->
            <button class="btn btn-primary btn-block" type="button" id="btn-signup"><i class="fas fa-user-plus"></i> Sign up New Account</button>
        </form>

            <!-- BOTON OLVIDASTE LA CONTRASENA -->           <!--BOTON OLVIDASTE LA CONTRASENA -->         <!-- BOTON OLVIDASTE LA CONTRASENA -->          
            <form action="/reset/password/" class="form-reset" method="post">
                {% csrf_token %} 
            <!-- CUADRO DE TEXTO E - M A I L -->           <!-- CUADRO DE TEXTO E - M A I L -->         <!-- CUADRO DE TEXTO E - M A I L -->   
                <input type="email" id="resetEmail" class="form-control" placeholder="Email address" required="" autofocus="">

            <!-- BOTON RESET PASSWORD -->           <!-- BOTON RESET PASSWORD -->         <!-- BOTON RESET PASSWORD -->
                <button class="btn btn-primary btn-block" type="submit">Reset Password</button>

            <!-- BOTON BACK -->           <!-- BOTON BACK -->         <!-- BOTON BACK -->
                <a href="#" id="cancel_reset"><i class="fas fa-angle-left"></i> Back</a>
            </form>
           
            
            <!-- SECCION SIGN UP -->           <!-- SECCION SIGN UP -->         <!--SECCION SIGN UP -->
            <form action='home' class="form-signup" method="post">
                {% csrf_token %} 
                <div class="social-login">
                <!-- B O T O N  D E  F A C E B O O K -->           <!-- B O T O N  D E  F A C E B O O K -->         <!-- B O T O N  D E  F A C E B O O K -->
                
                    <button class="btn facebook-btn social-btn" type="button"><span><i class="fab fa-facebook-f"></i> Sign up with Facebook</span> </button>
                </div>
                <div class="social-login">
                    <!-- B O T O N  D E  G O O G L E -->           <!-- B O T O N  D E  G O O G L E -->         <!-- B O T O N  D E  G O O G L E -->
                    <button class="btn google-btn social-btn" type="button"><span><i class="fab fa-google-plus-g"></i> Sign up with Google+</span> </button>
                </div>
                
                <p style="text-align:center">OR</p>

                <!-- CUADRO DE TEXTO FULL NAME -->           <!-- CUADRO DE TEXTO FULL NAME -->         <!-- CUADRO DE TEXTO FULL NAME -->
                <input type="text" id="user-name" class="form-control" placeholder="Full name" required="" autofocus="">

                <!-- CUADRO DE TEXTO E - M A I L -->           <!-- CUADRO DE TEXTO E - M A I L -->         <!-- CUADRO DE TEXTO E - M A I L -->
                <input type="email" id="user-email" class="form-control" placeholder="Email address" required autofocus="">

                <!-- CUADRO DE TEXTO C O N T R A S E N A -->           <!-- CUADRO DE TEXTO C O N T R A S E N A -->         <!-- CUADRO DE TEXTO C O N T R A S E N A -->
                <input type="password" id="user-pass" class="form-control" placeholder="Password" required autofocus="">

                <!-- CUADRO DE TEXTO R E P E T I R  C O N T R A S E N A -->           <!-- CUADRO DE TEXTO C O N T R A S E N A -->         <!-- CUADRO DE TEXTO C O N T R A S E N A -->
                <input type="password" id="user-repeatpass" class="form-control" placeholder="Repeat Password" required autofocus="">


                <!-- BOTON SIGN UP -->           <!-- BOTON SIGN UP -->         <!--BOTON SIGN UP -->
                <button class="btn btn-primary btn-block" type="submit"><i class="fas fa-user-plus"></i> Sign Up</button>

                <!-- BOTON BACK -->           <!-- BOTON BACK -->         <!-- BOTON BACK -->
                <a href="#" id="cancel_signup"><i class="fas fa-angle-left"></i> Back</a>
            </form>
            <br>
            
    </div>
    <p style="text-align:center">
        <a href="http://bit.ly/2RjWFMfunction toggleResetPswd(e){
    e.preventDefault();
    $('#logreg-forms .form-signin').toggle() // display:block or none
    $('#logreg-forms .form-reset').toggle() // display:block or none
}

function toggleSignUp(e){
    e.preventDefault();
    $('#logreg-forms .form-signin').toggle(); // display:block or none
    $('#logreg-forms .form-signup').toggle(); // display:block or none
}

$(()=>{
    // Login Register Form
    $('#logreg-forms #forgot_pswd').click(toggleResetPswd);
    $('#logreg-forms #cancel_reset').click(toggleResetPswd);
    $('#logreg-forms #btn-signup').click(toggleSignUp);
    $('#logreg-forms #cancel_signup').click(toggleSignUp);
})g" target="_blank" style="color:black">By Awmind</a>
    </p>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    
    <script src="{% static 'js/Javascript.js' %}"></script>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

templates/base.html
{% load static %}
<!doctype html>
<html class="no-js" lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{{ title }}</title>
    {% if stripe_public_key %}
    <meta name="stripe_public_key" content="{{ stripe_public_key }}">
    {% endif %}
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.svg' %}">
    
    <!-- CSS 
    ========================= -->
    {% block css %}
    <!--bootstrap min css-->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!--owl carousel min css-->
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <!--slick min css-->
    <link rel="stylesheet" href="{% static 'css/slick.css' %}">
    <!--magnific popup min css-->
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <!--font awesome css-->
    <link rel="stylesheet" href="{% static 'css/font.awesome.css' %}">
    <!--ionicons css-->
    <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">
    <!--linearicons css-->
    <link rel="stylesheet" href="{% static 'css/linearicons.css' %}">
    <!--animate css-->
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <!--jquery ui min css-->
    <link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}">
    <!--slinky menu css-->
    <link rel="stylesheet" href="{% static 'css/menu.css' %}">
    <!--plugins css-->
    <link rel="stylesheet" href="{% static 'css/plugins.css' %}">
    
    <!-- Main Style CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/Estilo_Log_In.css' %}">
    {% endblock %}
</head>

<body>
    {% include 'navbar.html' %}

    {% include 'messages.html' %}

    {% block breadcrumb %}
    {% endblock %}

      {% block content %}
      {% endblock %}
   
      {% block javascript %}
    <!-- JS
    ============================================ -->
        
    <!--modernizr min js here-->
    <script src="{% static 'js/vendor/modernizr-3.7.1.min.js' %}"></script>        
    <!-- Place your kit's code here -->
     <script src="https://kit.fontawesome.com/cff0fb316f.js" crossorigin="anonymous"></script>
    <!--jquery min js-->
    <script src="{% static 'js/vendor/jquery-3.4.1.min.js' %}"></script>
    <!--popper min js-->
    <script src="{% static 'js/popper.js' %}"></script>
    <!--bootstrap min js-->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!--owl carousel min js-->
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <!--slick min js-->
    <script src="{% static 'js/slick.min.js' %}"></script>
    <!--magnific popup min js-->
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <!--counterup min js-->
    <script src="{% static 'js/jquery.counterup.min.js' %}" ></script>
    <!--jquery countdown min js-->
    <script src="{% static 'js/jquery.countdown.js' %}"></script>
    <!--jquery ui min js-->
    <script src="{% static 'js/jquery.ui.js' %}"></script>
    <!--jquery elevatezoom min js-->
    <script src="{% static 'js/jquery.elevatezoom.js' %}"></script>
    <!--isotope packaged min js-->
    <script src="{% static 'js/isotope.pkgd.min.js' %}"></script>
    <!--slinky menu js-->
    <script src="{% static 'js/slinky.menu.js' %}"></script>
    <!-- Plugins JS -->
    <script src="{% static 'js/plugins.js' %}"></script>

    <!-- Main JS -->
    <script src="{% static 'js/main.js' %}"></script>

    <!-- Categorias -->
    <script src="{% static 'js/slidermenu.js' %}"></script>
    {% endblock %}
</body>
</html>

templates/messages.html
{% if messages %}
  {% for message in messages %}
    <div class="alert {% if message.tags == 'success'%}alert-success{%else%}alert-danger{%endif%}">
      <button type="button" class="close" data-dismiss="alert">x</button>
      {{ message }}
    </div>
  {% endfor %}
{% endif %}

templates/navbar1.html
{% url 'login' as login %}
{% url 'register' as register %}
{% url 'carts:cart' as cart %}
{% url 'shipping_addresses:shipping_addresses' as shipping_addresses %}
{% url 'orders:completeds' as completeds %}
{% url 'billing_profiles:billing_profiles' as billing_profiles %}

<nav class="navbar navbar-expand-md bg-dark navbar-dark">
  <a href="{% url 'index' %}" class="navbar-brand">Exportellus</a>

  <button type="button" name="button" class="navbar-toggler navbar-toggler-right" data-toggle="collapse" data-target="#navb">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div id="navb" class="navbar-collapse collapse hide">

    <ul class="navbar-nav">
      <li class="nav-item {% if request.path == cart%}active{% endif %}">
        <a class="nav-link" href="{{ cart }}">
          Mi carrito <span class="fas fa-shopping-cart"></span>
        </a>
      </li>
      {% if user.is_authenticated %}

        <li class="nav-item {% if request.path == shipping_addresses%}active{% endif %}">
          <a class="nav-link" href="{{ shipping_addresses }}">
            Mis direcciones <span class="fas fa-location-arrow"></span>
          </a>
        </li>

        <li class="nav-item {% if request.path == completeds %}active{% endif %}">
          <a class="nav-link" href="{{ completeds }}">
            Mis pedidos <span class="fas fa-shipping-fast"></span>
          </a>
        </li>

        <li class="nav-item {% if request.path == billing_profiles %}active{% endif %}">
          <a class="nav-link" href="{{ billing_profiles }}">
            Mis métodos de pago <span class="fab fa-cc-stripe"></span>
          </a>
        </li>

      {% endif %}
    </ul>

    <ul class="nav navbar-nav ml-auto">
      {% if user.is_authenticated %}
        <li class="navbar-item">
          <a href="{% url 'logout' %}" class="nav-link">
            <span class="fas fa-sign-in-alt"></span>
            Logout</a>
        </li>
      {% else %}
        <li class="navbar-item {% if request.path == login %}active{% endif %}">
          <a href="{{ login }}" class="nav-link">
            <span class="fas fa-user"></span>
            Login</a>
        </li>

        <li class="navbar-item {% if request.path == register %}active{% endif %}">
          <a href="{{ register }}" class="nav-link">
            <span class="fas fa-user-plus"></span>
            Registro</a>
        </li>
      {% endif %}
    </ul>

  </div>

</nav>

templates/navbar2.html
{% url 'login' as login %}
{% url 'register' as register %}
{% url 'carts:cart' as cart %}
{% url 'shipping_addresses:shipping_addresses' as shipping_addresses %}
{% url 'orders:completeds' as completeds %}
{% url 'billing_profiles:billing_profiles' as billing_profiles %}

<div class="item0 header">
  <div class="logo-caja">
      <a href="{% url 'index' %}"><img class="logo" src="static/iconos/logoexportellus.svg" alt=""></a>
  </div>
  <form action="{% url 'products:search' %}" class="barrayboton">
      <input class="barrabusqueda-search" type="search" placeholder="Search" aria-label="Search" value="{{ query }}">
      <input class="barrabusqueda-ubicacion" type="search" placeholder="Ubiacion" aria-label="Search">
      <button class="boton-search" type="submit">Search</button>
  </form>
  <div class="opciones">
      {% if user.is_authenticated %}
      <div class="login-caja">                    
              <button class="dropdownbutton" class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  ¡Hola Gabriel!
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item {% if request.path == shipping_addresses%}active{% endif %}" href="{{ shipping_addresses }}">Mis direcciones</a>
                <a class="dropdown-item {% if request.path == completeds %}active{% endif %}" href="{{ completeds }}">Mis compras</a>
                <a class="dropdown-item {% if request.path == sales %}active{% endif %}" href="{{ sales }}">Mis ventas</a>
                <a class="dropdown-item {% if request.path == configuracion %}active{% endif %}" href="{{ configuracion }}">Configuracion</a>
                <a class="dropdown-item {% if request.path == logout %}active{% endif %}" href="{% url 'index' %}">Cerrar sesion</a>
              </div>

      </div>

      <div href="" class="carritoheader {% if request.path == cart%}active{% endif %}">
          <div class="carrito">
              <a href="{{ cart }}"><img class="carrito1" src="static/iconos/carrito.svg"></a>
          </div>
      </div>

      {% else %}
      <div class="login-caja">                    
          <a href="{{ login }}"><button class="main_button {% if request.path == login %}active{% endif %}">
              Iniciar sesion
          </button></a>
      </div>

      <div class="login-caja">                    
          <a href="{{ register}}"><button class="main_button {% if request.path == register %}active{% endif %}">
              Resgistrarme
          </button></a>
      </div>

      {% endif %}
  </div>
  

</div>

templates/navbar7.html
{% url 'login' as login %}
{% url 'register' as register %}
{% url 'carts:cart' as cart %}
{% url 'shipping_addresses:shipping_addresses' as shipping_addresses %}
{% url 'orders:completeds' as completeds %}
{% url 'billing_profiles:billing_profiles' as billing_profiles %}

<div class="item1 header">
  <div class="logo-caja">
      <a href="{% url 'index' %}"><img class="logo" src="static/iconos/logoexportellus.svg" alt=""></a>
  </div>
  {% include 'products/snippets/search.html' %}
  <div class="opciones">
      {% if user.is_authenticated %}
      <div class="login-caja">                    
              <button class="dropdownbutton" class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  ¡Hola Luis!
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item {% if request.path == shipping_addresses%}active{% endif %}" href="{{ shipping_addresses }}">Mis direcciones</a>
                <a class="dropdown-item {% if request.path == completeds %}active{% endif %}" href="{{ completeds }}">Mis pedidos</a>
                <a class="dropdown-item {% if request.path == sales %}active{% endif %}" href="{{ sales }}">Mis ventas</a>
                <a class="dropdown-item {% if request.path == billing_profiles %}active{% endif %}" href="{{ billing_profiles }}">Mis formas de pago</a>
                <a class="dropdown-item {% if request.path == configuracion %}active{% endif %}" href="{{ configuracion }}">Configuracion</a>
                <a class="dropdown-item {% if request.path == logout %}active{% endif %}" href="{% url 'index' %}">Cerrar sesion</a>
              </div>

      </div>

      <div href="" class="carritoheader {% if request.path == cart%}active{% endif %}">
          <div class="carrito">
              <a href="{{ cart }}"><img class="carrito1" src="static/iconos/carrito.svg"></a>
          </div>
      </div>

      {% else %}
      <div class="login-caja">                    
          <a href="{{ login }}"><button class="main_button {% if request.path == login %}active{% endif %}">
              Iniciar sesion
          </button></a>
      </div>

      <div class="login-caja">                    
          <a href="{{ register }}"><button class="main_button {% if request.path == register %}active{% endif %}">
              Resgistrarme
          </button></a>
      </div>

      {% endif %}
  </div>
  

</div>